const express = require('../index')
const router = express.Router()
const controller = require('../controller/controller')
// const app = express()
// const {server }= require('../index')

router.use((req, res, next) => {
     next() 
  })

router.get('/',controller.home )
router.post('/login',controller.login)
router.post('/register',controller.register)
router.post('/updateprofilewithImage',controller.updateprofile_withImage)
router.post('/updateprofilenoImage',controller.updateprofile_noImage)
router.post('/profile',controller.profile)
router.get('/search',controller.search)
router.post('/insertfindhouse',controller.insertfindhouse)
router.post('/insertcatlost',controller.insertcatlost)
router.get('/news',controller.news)
router.get('/home_news',controller.newshome)
router.post('/insertnews',controller.insertnews)
router.get('/mypost/:id',controller.mypost)
router.get('/allpost',controller.allpost)
router.put('/editnews',controller.editnews)

router.put('/soft_delete/:id', controller.softdel)
router.put('/deny_post/:id', controller.denypost)
router.put('/accept_post/:id', controller.acceptpost)
router.put('/softdelnews/:id', controller.softdelnews)
router.get('/home_find', controller.homefindhouse)
router.get('/home_lost', controller.homecatlost)
router.get('/more_findhouse', controller.more_findhouse)
router.get('/catlost_more', controller.more_catlost)
router.put('/updatepostfindhouse', controller.updatePostFindhouse )
router.put('/updatepostlostcat', controller.updateLostCat)
module.exports = router